# Generated by Django 3.0.8 on 2020-08-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_auto_20200812_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
